### ISSUE TITLE
Support .artifacts directory scheme in .NET 8:

### ISSUE THREAD

**Issue by kuiperzone** [kuiperzone/AvantGarde#24]
See:

https://github.com/dotnet/designs/blob/simplify-output-paths-2/accepted/2023/simplify-output-paths.md

**Comment by kuiperzone** [comment]
Done

**Comment by Dryadxon** [comment]
There are two main changes with .NET 8 preview 4:
- The default path for the new layout is `artifacts` instead of `.artifacts`;
- The ability to enable the feature from Project files, instead of Directory.Build.props, was removed.

Source: https://devblogs.microsoft.com/dotnet/announcing-dotnet-8-preview-4/#sdk-simplified-output-path-updates

**Comment by kuiperzone** [comment]
>The default path for the new layout is artifacts instead of .artifacts;

Thank you for the update. This is a trivial change.

>The ability to enable the feature from Project files, instead of Directory.Build.props, was removed.

AvantGarde should (hopefully) find the binary whether it is "bin" or "artifacts" as it is, and should not need any change to read the props or project files.

**Comment by kuiperzone** [comment]
Fixed
